export const musicalInstruments = [
  "Accordion",
  "Bagpipes",
  "Banjo",
  "Banjo cello",
  "Bass banjo",
  "Five-stringed banjo",
  "Bluegrass banjo",
  "Four-stringed banjo",
  "Plectrum banjo",
  "Six-stringed banjo",
  "Tenor banjo",
  "Zither banjo",
  "Bass guitar",
  "Bassoon",
  "Clarinet",
  "Didgeridoo",
  "Drums",
  "Alto flute",
  "Bass flute",
  "Contra-alto flute",
  "Contrabass flute",
  "Hyperbass flute",
  "French horn",
  "Acoustic guitar",
  "Baritone guitar",
  "Bass guitar",
  "Classical guitar",
  "Electric guitar",
  "Electric bass guitar",
  "Flamenco guitar",
  "Harmonica",
  "Indian Banjo",
  "Mandocello",
  "Mandola",
  "Octave mandolin",
  "Melodica",
  "Octobass",
  "Organ",
  "Oud",
  "Pan Pipes",
  "Piano",
  "Piccolo",
  "Sopranino",
  "Great bass",
  "Contra bass",
  "Subcontra bass",
  "Singer",
  "Sub-subcontrabass",
  "Venova",
  "Sarangi",
  "Sarinda",
  "Santoor",
  "Sarod",
  "Alto saxophone",
  "Baritone saxophone",
  "Bass saxophone",
  "Contrabass saxophone",
  "Sopranino saxophone",
  "Soprano saxophone",
  "Tenor saxophone",
  "Tubax",
  "Sitar",
  "Synthesizer",
  "Tabla",
  "Tambourine",
  "Timpani",
  "Triangle",
  "Sopranino trombone",
  "Soprano trombone",
  "Alto trombone",
  "Tenor trombone",
  "Bass trombone",
  "Contrabass trombone",
  "Valve trombone",
  "Renaissance trombone",
  "Soprano trumpet",
  "Bass trumpet",
  "Baroque trumpet",
  "Bass trumpet",
  "Rotary valve trumpet",
  "Bass tuba",
  "Contrabass tuba",
  "Subcontrabass tuba",
  "Pocket ukulele",
  "Soprano ukulele",
  "Concert ukulele",
  "Tenor ukulele",
  "Baritone ukulele",
  "Bass ukulele",
  "Piccolo violino",
  "Viola",
  "Tenor viola",
  "Tenor violin",
  "Baritone violin",
  "Electric violin",
  "Piccolo cello",
  "Whamola",
  "Xylophone",
  "Zither",
];
